"""add satisfaction field

Revision ID: e4222f79264a
Revises: ca72df19df31
Create Date: 2024-02-25 05:24:03.861411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4222f79264a'
down_revision: Union[str, None] = 'ca72df19df31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('satisfaction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'satisfaction')
    # ### end Alembic commands ###
